DB_HOST: "database"
DB_USER: postgres
DB_PORT: 5432
DB_PASSWORD: postgres
DB_NAME: maosproject
DB_SSL_MODE: prefer
SECRET_KEY: veryStrongSecretKey
BASE_URL: http://localhost:8080
SMTP_HOST: mailhog
SMTP_PORT: 1025
FROM_EMAIL: no-reply@maos.io
EMAIL_PASSWORD: 
ENV: development