version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
    networks:
      - maos-cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    env_file:
      - .env

  database:
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maosproject
    restart: always
    networks:
      - maos-cloud-network
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP 
    networks:
      - maos-cloud-network
networks:
  maos-cloud-network:
    driver: bridge
    