version: '3.8'

services:
  database:
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maosproject
    restart: always
    networks:
      - maos-cloud-network
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - maos-cloud-network
networks:
  maos-cloud-network:
    driver: bridge
    