version: '3.8'

services:
  test_database:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maosproject
    restart: always
    networks:
      - maos-cloud-network
