version: '3.7'

services:
  database:
    image: postgres:14
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maosproject
    restart: always
    networks:
      - maos-cloud-network
networks:
  maos-cloud-network:
    drive: bridge
    